videohost/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from .views import *
from videoru import settings

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('', feed, name='feed'),
    path('upload/', upload_video, name='upload_video'),
    path('video/<int:video_id>/', video_detail, name='video_detail'),
    path('video_edit/<int:video_id>/', video_edit, name='video_edit'),
    path('playlist/<int:playlist_id>/', playlist_detail, name='playlist_detail'),
    path('my_channel_videos/', channel_videos, name='channel_videos'),
    path('my_channel_settings/', my_channel_settings, name='my_channel_settings'),
    path('views_history/', views_history, name='views_history'),
    path('my_subscriptions/', my_subscriptions, name='my_subscriptions'),
    #path('video/<int:video_id>', video, name='video')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videoru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('videohost.urls')),
]

videohost/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    nick = models.CharField(max_length=255, unique=True, verbose_name='Никнейм')
    name = models.CharField(max_length=255, blank=True, verbose_name='Имя')
    surname = models.CharField(max_length=255, blank=True, verbose_name='Фамилия')
    age = models.CharField(max_length=2, blank=True, verbose_name='Возраст')
    avatar = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, verbose_name='Аватар')
    cover = models.ImageField(upload_to='images/avatar/%Y/%m/%d/', blank=True, verbose_name='Обложка канала')
    about = models.CharField(blank=True, max_length=1000, verbose_name='Описание')


    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профиль'
        ordering = ['user']

class Subscription(models.Model):
    subscriber = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='subscriptions', verbose_name='Подписчик')
    channel = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='subscribers', verbose_name='Канал')

    class Meta:
        verbose_name = 'Подписки'
        verbose_name_plural = 'Подписки'


class Video(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название видео')
    preview = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True, verbose_name='Превью')
    video_file = models.FileField(upload_to='videos/%Y/%m/%d/', blank=True, verbose_name='Видеофайл')
    author = models.ForeignKey('Profile', on_delete=models.CASCADE, verbose_name='Автор')
    views_count = models.PositiveIntegerField(verbose_name='Кол-во просмотров', default=0)
    date_load = models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')
    description = models.CharField(max_length=3000, verbose_name='Описание', blank=True)
    comments = models.ManyToManyField('Comment', related_name='video_comments', blank=True, verbose_name='Комментарии')
    playlist = models.ManyToManyField('Playlist', related_name='playlist', blank=True, verbose_name='Плейлист')
    tags = models.CharField(max_length=255, blank=True, verbose_name='Тэги')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'
        ordering = ['date_load']


class Category(models.Model):
    category = models.CharField(max_length=100, db_index=True, verbose_name='Категория')

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'


class Comment(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE, verbose_name='Видео')
    author = models.ForeignKey('Profile', on_delete=models.CASCADE, verbose_name='Автор комментария')
    text = models.TextField(verbose_name='Текст комментария')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    class Meta:
        verbose_name = 'Комментарии'
        verbose_name_plural = 'Комментарии'
        ordering = ['created_at']


class Playlist(models.Model):
    CHOICES = [
        ('Доступно всем', 'Доступно всем'),
        ('Доступно только мне', 'Доступно только мне'),
        ('Доступно по ссылке', 'Доступно по ссылке'),
    ]

    name = models.CharField(max_length=255, verbose_name='Название')
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name='video_playlist', verbose_name='Видео')
    creator = models.ForeignKey('Profile', on_delete=models.CASCADE, verbose_name='Создатель')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    description = models.CharField(max_length=255, blank=True, verbose_name='Описание')
    access = models.TextField(choices=CHOICES, verbose_name='Права доступа')
    #saved = models.Foreignkey('Profile', on_delete=models.CASCADE, verbose_name='Сохранили')

    class Meta:
        verbose_name = 'Плейлисты'
        verbose_name_plural = 'Плейлисты'
        ordering = ['created_at']

class ViewHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    viewed_at = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'История просмотров'
        verbose_name_plural = 'История просмотров'

videohost/forms.py
from django import forms
from django.contrib.auth.models import *

from .models import *


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Password don\'t match")
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nick', 'name', 'surname', 'age', 'avatar', 'cover', 'about']

class VideoUploadForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'preview', 'video_file', 'description', 'tags', 'cat']

class VideoEditForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'preview', 'video_file', 'description', 'tags', 'cat']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class EditCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

videohost/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import *
from .models import *


@login_required
def dashboard(request):
    videos = Video.objects.all()
    profiles = Profile.objects.filter(user=request.user)  # берем только профиль юзера, который зашел


    template = 'videohost/dashboard.html'
    content = {
        'videos': videos,
        'profiles': profiles,
        'title': 'Мой канал'
    }

    return render(request, template, content)

def channel_videos(request):
    videos = Video.objects.all()
    profiles = Profile.objects.all()
    template = 'videohost/my_channel_videos.html'
    content = {
        'videos': videos,
        'profiles': profiles,
        'title': 'Мои видео'
    }

    return render(request, template, content)

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)

            new_user.set_password(user_form.cleaned_data['password'])

            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, 'videohost/register_done.html', {'new_user': new_user, 'title': 'Регистрация'})
    else:
        user_form = UserRegistrationForm
    return render(request, 'videohost/register.html', {'user_form': user_form, 'title': 'Регистрация'})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    template = 'videohost/edit.html'
    content = {
        'user_form': user_form,
        'profile_form': profile_form,
        'title': 'Редактировать канал'
    }
    return render(request, template, content)

def feed(request):

    videos = Video.objects.all()
    profiles = Profile.objects.all()

    # Проверяем, есть ли поисковой запрос в URL
    search_query = request.GET.get('search', None)

    # Фильтруем видео по запросу
    if search_query:
        videos = videos.filter(title__icontains=search_query)

    # система сортировки видео
    sort_option = request.GET.get('sort', None)
    if sort_option == 'newest':
        videos = videos.order_by('-date_load')  # сначала новые
    elif sort_option == 'oldest':
        videos = videos.order_by('date_load')  # сначала старые
    elif sort_option == 'max_views': #
        videos = videos.order_by('-views_count')

    template = 'videohost/feed.html'
    content = {
        'videos': videos,
        'profiles': profiles,
        'title': 'Главная'
    }
    return render(request,  template, content)


def upload_video(request):
    if request.method == 'POST':
        form = VideoUploadForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the video and associate it with the current user's profile
            video = form.save(commit=False)
            video.author = request.user.profile  # Assuming you have a one-to-one relationship between User and Profile
            video.save()
            return redirect('dashboard')  # Redirect to a page displaying the list of videos
    else:
        form = VideoUploadForm()

    template = 'videohost/upload_video.html'
    content = {
        'form': form,
        'title': 'Загрузить видео'
    }
    return render(request, template, content)

def video_detail(request, video_id):
    video = get_object_or_404(Video, id=video_id)
    comments_model = Comment.objects.all()
    # мы знаем конкретное видео, video.author - автор видео, соответственно этот канал мы ищем в модели и выводим список его подписчиков
    subscription = Subscription.objects.filter(channel=video.author)
    # проверяем является ли пользователь, который отправляет запрос(request.user.profile) подписчиком канала
    if request.user.is_authenticated:
        subscriber = Subscription.objects.filter(channel=video.author, subscriber=request.user.profile)
        ViewHistory.objects.create(user=request.user, video=video)
    else:
        subscriber = Subscription.objects.all()
    profiles = Profile.objects.all()
    video.views_count += 1
    video.save()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.video = video
            comment.author = request.user.profile
            comment.save()

        del_comment_id = request.POST.get('del_comment_id', None)
        if del_comment_id:
            comment_to_delete = get_object_or_404(Comment, id=del_comment_id)
            comment_to_delete.delete()

        subscribe = request.POST.get('subscribe', None)
        if subscribe == 'sub':
            # Получаем экземпляры профилей для текущего пользователя и автора видео

            subscriber_profile = request.user.profile
            channel = video.author
            # Создаем объект подписки
            subscription = Subscription(subscriber=subscriber_profile, channel=channel)
            subscription.save()

        unsubscribe = request.POST.get('unsubscribe', None)
        if unsubscribe == 'un-sub':
            subscription.filter(channel=video.author, subscriber=request.user.profile).delete()

        return redirect('video_detail', video_id=video_id)
    else:
        form = CommentForm()

    template = 'videohost/video_detail.html'
    content = {
        'video': video,
        'form': form,
        'comments_model': comments_model,
        'subscription': subscription,
        'profiles': profiles,
        'subscriber': subscriber,
        'title': video.title
    }
    return render(request, template, content)


def video_edit(request, video_id):
    video = get_object_or_404(Video, id=video_id)

    if request.method == 'POST':
        video_edit_form = VideoEditForm(request.POST, request.FILES, instance=video)
        if video_edit_form.is_valid():
            video_edit_form.save()
            del_video_option = request.POST.get('del', None)
            if del_video_option == 'del_video':
                video.delete()
                return redirect('channel_videos')
    else:
        video_edit_form = VideoEditForm(instance=video)

    template = 'videohost/video_edit.html'
    content = {
        'video_edit_form': video_edit_form,
        'video': video,
        'title': 'Редактировать видео'
        }
    return render(request, template, content)

def playlist_detail(request, playlist_id):
    playlist = get_object_or_404(Playlist, id=playlist_id)
    template = 'videohost/playlist_detail.html'
    content = {
        'playlist': playlist,
        'title': playlist.video.title
    }
    return render(request, template, content)

def my_channel_settings(request):
    profiles = Profile.objects.all()

    template = 'videohost/my_channel_settings.html'
    content = {
        'profiles': profiles,
        'title': 'Настройки канала'
    }
    return render(request, template, content)

@login_required
def views_history(request):
    template = 'videohost/views_history.html'
    history = ViewHistory.objects.filter(user=request.user)
    content = {
        'history': history,
        'title': 'История просмотров'
    }
    return render(request, template, content)

@login_required
def my_subscriptions(request):
    my_subscriptions = Subscription.objects.filter(subscriber=request.user.profile)
    video = Video.objects.all()
    template = 'videohost/my_subscriptions.html'
    content = {
        'my_subscriptions': my_subscriptions,
        'video': video,
        'title': 'Мои подписки'
    }
    return render(request, template, content)

videohost/templates/videohost/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" href="{% static 'videohost/css/styles.css'%}" rel="stylesheet">
    <title>{{ title }}</title>
</head>
<body>

<div id="header-log-in">
     <span>
         {% if request.user.is_authenticated %}
         <center>
             <a href="{% url 'dashboard' %}" class="header-link">{{ request.user.username }}</a><br>
             <a href="{% url 'logout' %}" class="header-link">Выход</a>
             {% else %}
             <a href="{% url 'login' %}" class="header-link">Вход</a>
         </center>
         {% endif %}
     </span>
</div>
<div class="menu">
    <ul>
        <li><a href="{% url 'feed' %}">Главная</a></li>
        <li><a href="{% url 'dashboard' %}">Мой канал</a></li>
        <li><a href="{% url 'channel_videos' %}">Мои видео</a></li>
        <li><a href="{% url 'my_subscriptions' %}">Подписки</a></li>
        <li><a href="{% url 'views_history' %}">История просмотров</a></li>
        <li><a href="#">Плейлисты</a></li>
    </ul>
</div>

{% block content %}
{% endblock %}
</body>
</html>

videohost/templates/videohost/dashboard.html
{% extends 'videohost/base.html' %}
{% block content %}

{% for p in profiles %}
<div class="channel_cover">
  <!-- <img src="{{ p.cover.url }}" alt="cover"> -->
</div>
<div class="my_channel_header">
   <div class="channel_avatar">
         <img src="{{ p.avatar.url }}" alt="avatar">
   </div>
</div>
{% endfor %}
<div class="my_channel_navigation">
    <ul>
       <li><a href="{% url 'channel_videos' %}">Мои видео</a></li>
       <li><a href="#">Описание</a></li>
       <li><a href="#">Аналитика</a></li>
       <li><a href="{% url 'my_channel_settings' %}">Настройки</a></li>
   </ul>
</div>
<a href="{% url 'upload_video' %}" class="upload-video-button">+ Добавить видео</a>
<a href="#" class="create-playlist-button">Создать плейлист</a>

{% endblock %}

videohost/templates/videohost/edit.html
{% extends "videohost/base.html" %}
{% block title %}Edit your account{% endblock %}
{% block content %}
<div class="edit-profile">
 <h1>Редактировать профиль</h1>
 <form action="." method="post" enctype="multipart/form-data">
 {{ user_form.as_p }}
 {{ profile_form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Сохрнаить"></p>
 </form>
</div>
{% endblock %}

videohost/templates/videohost/feed.html
{% extends 'videohost/base.html' %}
{% block content %}

    <div class="search-form">
        <center>
            <form method="get" action="{% url 'feed' %}">
                <input type="text" name="search" placeholder="Поиск по названию" value="{{ request.GET.search }}" class="search-input">
                <button type="submit" class="button">Искать</button>
            </form>
        </center>
    </div>

    <div class="filters">
        <form method="get" action="{% url 'feed' %}">
            <button type="submit" name="sort" value="newest">Сначала новые</button>
            <button type="submit" name="sort" value="oldest">Сначала старые</button>
            <button type="submit" name="sort" value="max_views">Больше просмотров</button>
        </form>
    </div>


<div class="feed-videos">
    {% for v in videos %}
    <div class="block-video">
        <a href="{% url 'video_detail' v.id %}">
            <img src="{{ v.preview.url }}" alt="preview">
            <div class="block-video-description">
                <h3>{{ v.title }}</h3>
                <p>Автор: {{ v.author.nick }}</p>
                <p>{{ v.views_count }} просмотров  || {{ v.date_load }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>


{% endblock %}

videohost/templates/videohost/my_channel_settings.html
{% extends 'videohost/base.html' %}
{% block content %}

<div class="channel_cover"></div>
<div class="my_channel_header">
   <div class="channel_avatar"></div>
</div>
<div class="my_channel_navigation">
   <ul>
       <li><a href="{% url 'channel_videos' %}">Мои видео</a></li>
       <li><a href="#">Описание</a></li>
       <li><a href="#">Аналитика</a></li>
       <li><a href="{% url 'my_channel_settings' %}">Настройки</a></li>
   </ul>
</div>

<div class="my_channel_settings_navigation">
    <ul>
        <li><a href="{% url 'edit' %}">Редактировать мой канал</a></li>
        <li><a href="{% url 'password_change' %}">Изменить пароль</a></li>
    </ul>
</div>




{% endblock %}

videohost/templates/videohost/my_channel_videos.html
{% extends 'videohost/base.html' %}
{% block content %}

<div class="channel_cover"></div>

<div class="my_channel_navigation">
   <ul>
       <li><a href="{% url 'channel_videos' %}">Мои видео</a></li>
       <li><a href="#">Описание</a></li>
       <li><a href="#">Аналитика</a></li>
       <li><a href="{% url 'my_channel_settings' %}">Настройки</a></li>
   </ul>
</div>

{% for v in videos %}
{% if request.user.username == v.author %}
<div class="block-video">
    <a href="{% url 'video_detail' v.id %}">
        <ul>
                <li><img src="{{ v.preview.url }}" alt="preview"></li>
                <li>{{ v.title }}</li>
                <li> {{ v.author.nick }}</li>
                <li>{{ v.views_count }}</li>
                <li>{{ v.date_load }}</li>
                <li><a href="{% url 'video_edit' v.id %}">Редактировать видео</a></li>
        </ul>
    </a>
</div>
{% endif %}
{% endfor %}



{% endblock %}

videohost/templates/videohost/my_playlists.html
{% extends 'videohost/base.html' %}
{% block content %}
{% for p in my_playlists %}
<ul>
  <li>{{ p.playlist_preview }}</li>
</ul>
{% endblock %}

videohost/templates/videohost/my_subscriptions.html
{% extends 'videohost/base.html' %}
{% block content %}
<div class="feed-videos" id="my-subscriptions-feed">
    {% for m in my_subscriptions %}
        {% for v in video %}
            {% if v.author == m.channel %}
                <div class="block-video">
                    <a href="{% url 'video_detail' v.id %}">
                        <img src="{{ v.preview.url }}" alt="preview">
                        <div class="block-video-description">
                            <h3>{{ v.title }}</h3>
                            <p>Автор: {{ v.author }}</p>
                            <p>{{ v.views_count }} просмотров  || {{ v.date_load }}</p>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    {% endfor %}
</div>



{% endblock %}

videohost/templates/videohost/playlist_detail.html
{% extends 'videohost/base.html' %}
{% block content %}
{% if playlist.access == 'Доступно только мне' and request.user == playlist.creator.user or playlist.access == 'Доступно всем' or playlist.access == 'Доступно по ссылке' %}
Страница плейлиста {{ playlist.name }}
{% endif %}

{% endblock %}

videohost/templates/videohost/register.html
{% extends "videohost/base.html" %}
{% block title %}Создать аккаунт{% endblock %}
{% block content %}
<div class="register-form">
 <form action="." method="post">
  <h1>Создать аккаунт</h1>
 {{ user_form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Создать аккаунт"></p>
 </form>
</div>
{% endblock %}

videohost/templates/videohost/register_done.html
{% extends "videohost/base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
 <h1>Welcome {{ new_user.first_name }}!</h1>
 <p>Your account has been successfully created.
 Now you can <a href="{% url 'login' %}">log in</a>.</p>
{% endblock %}

videohost/templates/videohost/upload_video.html
{% extends 'videohost/base.html' %}
{% block content %}

<form method="post" enctype="multipart/form-data" class="video-upload-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_title">Название:</label>
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="id_preview">Превью:</label>
        {{ form.preview }}
    </div>
    <div class="form-group">
        <label for="id_video_file">Видеофайл:</label>
        {{ form.video_file }}
    </div>
    <div class="form-group">
        <label for="id_description">Описание:</label>
        {{ form.description }}
    </div>
    <div class="form-group">
        <label for="id_tags">Тэги:</label>
        {{ form.tags }}
    </div>
    <div class="form-group">
        <label for="id_cat">Категория:</label>
        {{ form.cat }}
    </div>
    <button type="submit">Добавить видео</button>
</form>



{% endblock %}

videohost/templates/videohost/video_detail.html
{% extends 'videohost/base.html' %}
{% block content %}
<div>
        <ul>
            <div class="video-post">
                <li>{{ video.title }}</li>
                <li class="video-post-videofile">
                    <video width="800" height="500" controls>
                        <source src="{{ video.video_file.url }}" type="video/mp4">
                    </video>
                </li>
                <li>{{ video.views_count }} просмотров || {{ video.date_load }} </li>
                <li>
                    <img src="{{ video.author.avatar }}" id="video_detail_avatar"> <!-- Откорректриовать, url не работает -->
                    {{ video.author }}
                    {% if request.user.is_authenticated == True %}
                        {% if request.user.profile != video.author %}
                            <form method="post" action="{% url 'video_detail' video_id=video.id %}">
                                {% csrf_token %}
                                {% if subscriber %}
                                <!-- QuerySet не пустой, содержит какие-то объекты -->
                                    <button type="submit" name="unsubscribe" value="un-sub" class="sub-unsub-btn">Отписаться</button>
                                {% else %}
                                    <!-- QuerySet пустой -->
                                    <button type="submit" name="subscribe" value="sub" class="sub-unsub-btn">Подписаться</button>
                                {% endif %}
                            </form>
                        {% elif request.user.profile == video.author %}
                            <a href="{% url 'dashboard' %}">Мой канал</a>
                        {% endif %}
                    {% endif %}
                    {% if request.user.is_authenticated == False %}
                    <form action="{% url 'login' %}" method="get">
                        <button class="sub-unsub-btn">Подписаться</button>
                    </form>
                    {% endif %}
                </li>
                <li>{{ video.description }}</li>
            </div>
            <div class="video-post-add-comment">
                <form method="post" action="{% url 'video_detail' video_id=video.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Добавить комментарий</button>
                </form>
            </div>

            <div class="video-post-comments">
             <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for c in comments_model %}
                    {% if c.video.pk == video.id %}
                         <li>{{ c.text }} || {{ c.author }}  <button type="submit" name="del_comment_id" value="{{ c.id }}">Удалить комментарий</button></li>
                    {% endif %}
                {% endfor %}
             </form>
            </div>

        </ul>
</div>




{% endblock %}

videohost/templates/videohost/video_edit.html
{% extends "videohost/base.html" %}
{% block title %}Edit Video{% endblock %}
{% block content %}
  <h2>Edit Video</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ video_edit_form.as_p }}
    <button type="submit">Save Changes</button>
    <button type="submit" name="del" value="del_video">Удалить видео</button>
  </form>
{% endblock %}